<?php

namespace gestorBundle\Repository;

/**
 * profesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profesorRepository extends \Doctrine\ORM\EntityRepository
{
}
