gestor_homepage:
    path:     /
    defaults: { _controller: gestorBundle:Default:index }

all_empresa:
    path:     /empresa/all
    defaults: { _controller: gestorBundle:empresa:all }

#empresa_crear:
 #   path:     /empresa/new
 #   defaults: { _controller: gestorBundle:empresa:crearEmpresa }

empresa_nueva:
    path:     /empresa/new
    defaults: { _controller: gestorBundle:empresa:nuevaEmpresa }

empresa_msgExito:
    path:     /empresa/msgExito
    defaults: { _controller: gestorBundle:empresa:msgExito }

alumnosAll:
  path:       /alumno/all
  defaults: { _controller: gestorBundle:alumno:alumnosAll }

jsonempresas:
    path: /empresas
    defaults: {_controller: gestorBundle:empresasAPI:generarJSON}
    methods: [GET]

#creamos una ruta para poder mostrar todos los profesores,llamaremos al controlador profesores y dentro
#de el la función All

todosProfesores:
    path: /profesores/all
    defaults: {_controller: gestorBundle:profesores:all}

#creamos una ruta para poder mostrar todos los profesores,llamaremos al controlador profesores y dentro
#de el la función All

nuevoProfesor:
    path: /profesores/new
    defaults: {_controller: gestorBundle:profesores:nuevoProfesor}